export enum GameState{
    NOT_STARTED = 'NOT_STARTED',
    STARTED = 'STARTED',
    ADDING_PLAYERS = 'ADDING_PLAYERS',
    PLAYER_TURN = 'PLAYER_TURN',
    LEADERBOARD = 'LEADERBOARD',
    QUESTION = 'QUESTION',
    ENDED = 'ENDED'
}